[project]
name = "llm-data-pre-training"
version = "0.1.0"
description = "Project to showcase a data prep pipeline for LLM pretraining"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.12.15",
    "pydantic>=2.11.7",
    "tqdm>=4.67.1",
    "zstandard>=0.24.0",
]
