apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-data-pvc
  namespace: deepdive
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-ssd
  resources:
    requests:
      storage: 100Gi
